name: Lint
on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: pnpm install
        
      - name: Lint code
        run: pnpm lint